"""
MITRE ATT&CK Threat Intelligence Database — v2
================================================
120 techniques covering all 14 MITRE tactics.

Each entry includes:
  technique_id    MITRE ATT&CK technique (T-number)
  sub_id          Sub-technique ID if applicable
  name            Technique display name
  tactic          ATT&CK tactic(s)
  severity_score  CVSS v3.1-style base score (0–10)
  severity_label  Critical / High / Medium / Low
  prevalence      Real-world frequency 0–1 (based on CISA KEV + industry reports)
  apt_groups      Threat actor groups known to use this technique
  cve_examples    CVE identifiers associated with this technique (where applicable)
  categories      NCA ECC control categories this technique exploits
  nca_domains     Saudi NCA ECC control domain codes
  keywords        Rich keyword set for embedding enrichment
  description     Technical description
  mitigation      Recommended countermeasures
"""

THREAT_DB = [

    # ══════════════════════════════════════════════════════════════════════════════
    # INITIAL ACCESS
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1190",
        "sub_id": None,
        "name": "Exploit Public-Facing Application",
        "tactic": "Initial Access",
        "severity_score": 9.8,
        "severity_label": "Critical",
        "prevalence": 0.92,
        "apt_groups": ["APT33", "APT34", "FIN7", "Lazarus Group", "APT41"],
        "cve_examples": ["CVE-2021-44228 (Log4Shell)", "CVE-2021-26084 (Confluence)", "CVE-2022-26134"],
        "categories": ["firewall", "network", "patch"],
        "nca_domains": ["2-9", "2-11", "2-16", "2-21"],
        "keywords": "exploit vulnerability application web server internet exposed perimeter firewall bypass injection sql xss rce log4shell confluence exchange proxylogon proxyshell",
        "description": "Adversaries exploit security flaws in internet-facing systems (web apps, VPNs, Exchange servers) to gain an initial foothold. This is the most common initial access vector in enterprise breaches.",
        "mitigation": "Patch immediately; enforce WAF rules; reduce internet-facing attack surface; conduct regular external vulnerability scans."
    },
    {
        "technique_id": "T1133",
        "sub_id": None,
        "name": "External Remote Services",
        "tactic": "Initial Access / Persistence",
        "severity_score": 8.1,
        "severity_label": "High",
        "prevalence": 0.88,
        "apt_groups": ["APT33", "OilRig", "MuddyWater", "APT29", "Cozy Bear"],
        "cve_examples": ["CVE-2019-11510 (Pulse VPN)", "CVE-2023-46805 (Ivanti)"],
        "categories": ["firewall", "access", "network"],
        "nca_domains": ["2-8", "2-11", "2-12"],
        "keywords": "vpn rdp remote desktop access external service firewall rule port open ssh citrix terminal server jump host bastion",
        "description": "Threat actors abuse exposed remote access services (VPN, RDP, SSH, Citrix) — often with stolen credentials or exploiting known vulnerabilities — for persistent access.",
        "mitigation": "Enforce MFA on all remote services; patch VPN/gateway appliances; restrict source IP ranges; deploy CBA certificates."
    },
    {
        "technique_id": "T1566",
        "sub_id": "T1566.001",
        "name": "Spearphishing Attachment",
        "tactic": "Initial Access",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.95,
        "apt_groups": ["APT34", "Charming Kitten", "APT35", "Magic Hound", "Sandworm", "Lazarus"],
        "cve_examples": ["CVE-2017-11882 (Office Equation Editor)", "CVE-2022-30190 (Follina)"],
        "categories": ["antivirus", "logging"],
        "nca_domains": ["2-9", "2-10", "2-18"],
        "keywords": "phishing spearphishing email malicious attachment macro office word excel pdf zip archive social engineering targeted email lure",
        "description": "Targeted emails carrying weaponized attachments (macros, Office exploits, PDFs) are the most prevalent malware delivery method, frequently used against GCC/Saudi targets.",
        "mitigation": "Disable Office macros by default; sandbox email attachments; deploy advanced email filtering; user awareness training."
    },
    {
        "technique_id": "T1566",
        "sub_id": "T1566.002",
        "name": "Spearphishing Link",
        "tactic": "Initial Access",
        "severity_score": 8.1,
        "severity_label": "High",
        "prevalence": 0.91,
        "apt_groups": ["APT34", "APT35", "Charming Kitten", "APT33"],
        "cve_examples": [],
        "categories": ["antivirus", "logging"],
        "nca_domains": ["2-9", "2-10"],
        "keywords": "phishing link url credential harvest fake login page browser malicious website click social engineering oauth consent",
        "description": "Adversaries send emails with malicious links to credential-harvesting pages or drive-by download sites.",
        "mitigation": "Deploy URL filtering; enable Safe Links; use browser isolation; enforce phishing-resistant MFA."
    },
    {
        "technique_id": "T1195",
        "sub_id": "T1195.002",
        "name": "Supply Chain Compromise",
        "tactic": "Initial Access",
        "severity_score": 9.0,
        "severity_label": "Critical",
        "prevalence": 0.55,
        "apt_groups": ["APT29", "APT41", "Lazarus Group"],
        "cve_examples": ["CVE-2020-10148 (SolarWinds)", "CVE-2021-35211 (Kaseya)"],
        "categories": ["patch", "network"],
        "nca_domains": ["2-9", "2-23", "2-24"],
        "keywords": "supply chain software update trusted vendor third party compromise SolarWinds Kaseya build pipeline dependency injection",
        "description": "Attackers compromise software build pipelines or third-party vendors to distribute malware through trusted update channels.",
        "mitigation": "Verify software integrity (code signing); vet third-party vendors; monitor software update behavior; SBOM management."
    },
    {
        "technique_id": "T1078",
        "sub_id": None,
        "name": "Valid Accounts",
        "tactic": "Defense Evasion / Persistence / Initial Access",
        "severity_score": 9.1,
        "severity_label": "Critical",
        "prevalence": 0.97,
        "apt_groups": ["APT33", "APT34", "FIN7", "Lazarus", "CL0P"],
        "cve_examples": [],
        "categories": ["access"],
        "nca_domains": ["2-8"],
        "keywords": "credential account privilege access control identity user password authentication stolen default valid account compromised credential living off the land",
        "description": "Attackers use legitimate credentials obtained through phishing, purchasing on dark web, or brute force. This is the #1 technique in cloud breaches.",
        "mitigation": "Enforce phishing-resistant MFA (FIDO2); audit privileged accounts; implement PAM; monitor for impossible travel alerts."
    },
    {
        "technique_id": "T1189",
        "sub_id": None,
        "name": "Drive-by Compromise",
        "tactic": "Initial Access",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.60,
        "apt_groups": ["APT34", "APT37", "Lazarus"],
        "cve_examples": ["CVE-2021-30551 (Chrome)", "CVE-2021-21166 (Chrome)"],
        "categories": ["antivirus", "patch"],
        "nca_domains": ["2-9", "2-10", "2-16"],
        "keywords": "drive by browser exploit watering hole malicious website javascript exploit kit unpatched browser vulnerability",
        "description": "Adversaries compromise websites visited by targets, serving browser exploits to gain code execution without user interaction.",
        "mitigation": "Keep browsers and plugins patched; use browser isolation; deploy DNS filtering; disable unnecessary browser features."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # EXECUTION
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1059",
        "sub_id": "T1059.001",
        "name": "PowerShell Execution",
        "tactic": "Execution",
        "severity_score": 9.5,
        "severity_label": "Critical",
        "prevalence": 0.94,
        "apt_groups": ["APT33", "APT34", "Turla", "FIN7", "Cobalt Strike users"],
        "cve_examples": [],
        "categories": ["antivirus"],
        "nca_domains": ["2-9"],
        "keywords": "powershell execution fileless malware encoded command script execution obfuscation bypass AMSI endpoint evasion living off land LOLBIN",
        "description": "PowerShell is the most abused scripting interpreter. Attackers use encoded commands, AMSI bypass techniques, and in-memory execution to evade AV detection.",
        "mitigation": "Enable PowerShell Script Block Logging; enforce Constrained Language Mode; deploy EDR with behavioral detection; use AMSI."
    },
    {
        "technique_id": "T1059",
        "sub_id": "T1059.003",
        "name": "Windows Command Shell",
        "tactic": "Execution",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.90,
        "apt_groups": ["APT33", "OilRig", "Lazarus", "FIN7"],
        "cve_examples": [],
        "categories": ["antivirus"],
        "nca_domains": ["2-9"],
        "keywords": "cmd command shell batch file execution windows scripting host wscript cscript vbscript jscript",
        "description": "Adversaries use cmd.exe, batch files, and Windows scripting hosts to execute malicious commands and payloads.",
        "mitigation": "Restrict script execution via AppLocker/WDAC; log command-line events (4688); block WSH execution."
    },
    {
        "technique_id": "T1204",
        "sub_id": "T1204.002",
        "name": "Malicious File Execution",
        "tactic": "Execution",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.93,
        "apt_groups": ["APT34", "Lazarus", "Charming Kitten", "FIN7"],
        "cve_examples": ["CVE-2022-30190 (Follina MSDT)"],
        "categories": ["antivirus"],
        "nca_domains": ["2-9", "2-10"],
        "keywords": "malicious file user execution trojan dropper macro office document iso lnk shortcut fake invoice attachment",
        "description": "Users are tricked into opening malicious files disguised as legitimate documents, installers, or invoices.",
        "mitigation": "Deploy email sandboxing; restrict executable file types; use Mark-of-the-Web enforcement; train users."
    },
    {
        "technique_id": "T1047",
        "sub_id": None,
        "name": "WMI Execution",
        "tactic": "Execution",
        "severity_score": 8.1,
        "severity_label": "High",
        "prevalence": 0.75,
        "apt_groups": ["APT33", "APT34", "CrowdStrike-tracked groups"],
        "cve_examples": [],
        "categories": ["antivirus", "logging"],
        "nca_domains": ["2-9", "2-18"],
        "keywords": "WMI windows management instrumentation lateral execution remote command persistence subscriptions eventing log evasion",
        "description": "WMI provides a legitimate Windows mechanism for remote command execution and persistence that often bypasses AV.",
        "mitigation": "Monitor WMI activity; restrict WMI remote access; use sysmon for WMI event logging."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # PERSISTENCE
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1543",
        "sub_id": "T1543.003",
        "name": "Windows Service Creation",
        "tactic": "Persistence / Privilege Escalation",
        "severity_score": 7.8,
        "severity_label": "High",
        "prevalence": 0.72,
        "apt_groups": ["APT33", "Lazarus", "FIN7"],
        "cve_examples": [],
        "categories": ["antivirus", "logging"],
        "nca_domains": ["2-9", "2-18"],
        "keywords": "windows service creation persistence registry malware autostart boot startup service install",
        "description": "Attackers create or modify Windows services to execute malicious code on every system boot.",
        "mitigation": "Monitor service creation events (7045); use host-based IPS; restrict service installation rights."
    },
    {
        "technique_id": "T1547",
        "sub_id": "T1547.001",
        "name": "Registry Run Key Persistence",
        "tactic": "Persistence / Privilege Escalation",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.80,
        "apt_groups": ["APT33", "APT34", "Turla", "Lazarus"],
        "cve_examples": [],
        "categories": ["antivirus"],
        "nca_domains": ["2-9"],
        "keywords": "registry run key HKCU HKLM autostart startup persistence boot execute malware runonce shell",
        "description": "Malware adds entries to Windows Registry Run keys to survive reboots and maintain persistence.",
        "mitigation": "Monitor registry modifications (Sysmon event 13); use EDR behavioral rules; deploy application allowlisting."
    },
    {
        "technique_id": "T1505",
        "sub_id": "T1505.003",
        "name": "Web Shell",
        "tactic": "Persistence",
        "severity_score": 9.0,
        "severity_label": "Critical",
        "prevalence": 0.85,
        "apt_groups": ["APT34", "OilRig", "APT41", "Hafnium"],
        "cve_examples": ["CVE-2021-26855 (Exchange ProxyLogon)"],
        "categories": ["firewall", "patch", "network"],
        "nca_domains": ["2-9", "2-11", "2-21"],
        "keywords": "web shell backdoor aspx php jsp server persistence command execution upload file vulnerability exploitation web server",
        "description": "Attackers upload web shells to compromised servers as a persistent backdoor for remote command execution and lateral movement.",
        "mitigation": "Monitor for new web-accessible file creation; use file integrity monitoring; apply patches promptly; implement WAF."
    },
    {
        "technique_id": "T1098",
        "sub_id": None,
        "name": "Account Manipulation",
        "tactic": "Persistence",
        "severity_score": 8.4,
        "severity_label": "High",
        "prevalence": 0.78,
        "apt_groups": ["APT33", "OilRig", "APT29", "Scattered Spider"],
        "cve_examples": [],
        "categories": ["access"],
        "nca_domains": ["2-8"],
        "keywords": "account manipulation privilege escalation admin user modification access control IAM group membership role OAuth app registration backdoor account",
        "description": "Attackers add credentials, modify permissions, or register OAuth applications on existing accounts to maintain long-term access.",
        "mitigation": "Alert on privilege modifications; enforce separation of duties; review admin group membership; audit OAuth app permissions."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # PRIVILEGE ESCALATION
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1068",
        "sub_id": None,
        "name": "Exploitation for Privilege Escalation",
        "tactic": "Privilege Escalation",
        "severity_score": 9.1,
        "severity_label": "Critical",
        "prevalence": 0.82,
        "apt_groups": ["APT33", "Lazarus", "APT41", "FIN8"],
        "cve_examples": ["CVE-2021-34527 (PrintNightmare)", "CVE-2022-37969 (CLFS)", "CVE-2023-23376"],
        "categories": ["patch"],
        "nca_domains": ["2-16", "2-9"],
        "keywords": "privilege escalation kernel exploit unpatched cve elevation patch management local admin root system PrintNightmare CLFS win32k",
        "description": "Attackers exploit unpatched kernel or OS driver vulnerabilities to escalate from user to SYSTEM/root privileges.",
        "mitigation": "Prioritize OS and kernel patches within 48 hours; enforce least privilege; monitor privilege escalation events."
    },
    {
        "technique_id": "T1134",
        "sub_id": None,
        "name": "Access Token Manipulation",
        "tactic": "Defense Evasion / Privilege Escalation",
        "severity_score": 8.1,
        "severity_label": "High",
        "prevalence": 0.65,
        "apt_groups": ["APT33", "Cobalt Strike", "Metasploit"],
        "cve_examples": [],
        "categories": ["access"],
        "nca_domains": ["2-8"],
        "keywords": "token impersonation manipulation access control runas privilege process injection Windows token steal SeDebugPrivilege",
        "description": "Attackers manipulate Windows access tokens to impersonate other users or elevate to SYSTEM without needing credentials.",
        "mitigation": "Restrict token manipulation privileges; monitor token duplication events; use Credential Guard."
    },
    {
        "technique_id": "T1484",
        "sub_id": "T1484.001",
        "name": "Group Policy Modification",
        "tactic": "Defense Evasion / Privilege Escalation",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.58,
        "apt_groups": ["APT29", "Conti ransomware", "BlackCat"],
        "cve_examples": [],
        "categories": ["access"],
        "nca_domains": ["2-8", "2-9"],
        "keywords": "group policy GPO modification active directory domain admin privilege escalation GPP password push malware domain wide",
        "description": "Attackers with domain admin rights modify Group Policy Objects to distribute malware or disable security controls across the entire domain.",
        "mitigation": "Monitor GPO modifications; restrict GPO editing rights; alert on mass GPO deployment events."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # DEFENSE EVASION
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1562",
        "sub_id": "T1562.001",
        "name": "Disable Security Tools",
        "tactic": "Defense Evasion",
        "severity_score": 9.0,
        "severity_label": "Critical",
        "prevalence": 0.88,
        "apt_groups": ["Conti", "LockBit", "BlackCat", "APT33"],
        "cve_examples": [],
        "categories": ["antivirus", "logging"],
        "nca_domains": ["2-9", "2-18", "2-19"],
        "keywords": "disable antivirus security tool tamper protection real-time monitoring evasion defense impair kill EDR AV stop service registry key process termination",
        "description": "Ransomware groups and APTs systematically disable AV, EDR, and logging tools as the first action after gaining admin access.",
        "mitigation": "Enable tamper protection on security tools; protect security service accounts; alert on AV/EDR service state changes."
    },
    {
        "technique_id": "T1070",
        "sub_id": "T1070.001",
        "name": "Clear Windows Event Logs",
        "tactic": "Defense Evasion",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.82,
        "apt_groups": ["APT33", "APT34", "Lazarus", "BlackMatter"],
        "cve_examples": [],
        "categories": ["logging"],
        "nca_domains": ["2-18"],
        "keywords": "log deletion clear audit trail indicator removal forensic logging monitoring event wipe history wevtutil event log cleared",
        "description": "Attackers clear Windows Event Logs (System, Security, Application) immediately after intrusion to destroy forensic evidence.",
        "mitigation": "Forward logs to immutable centralized SIEM in real time; set write-once log storage; alert on log clearing events (1102, 104)."
    },
    {
        "technique_id": "T1070",
        "sub_id": "T1070.003",
        "name": "Clear Command History",
        "tactic": "Defense Evasion",
        "severity_score": 6.5,
        "severity_label": "Medium",
        "prevalence": 0.70,
        "apt_groups": ["APT33", "APT34", "APT41"],
        "cve_examples": [],
        "categories": ["logging"],
        "nca_domains": ["2-18"],
        "keywords": "command history clear bash history powershell history delete forensic anti-forensics command line audit",
        "description": "Attackers delete shell history files to remove evidence of commands executed during an intrusion.",
        "mitigation": "Use centralized command logging; enable auditing of shell history deletion; deploy Sysmon for process command-line capture."
    },
    {
        "technique_id": "T1055",
        "sub_id": None,
        "name": "Process Injection",
        "tactic": "Defense Evasion / Privilege Escalation",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.85,
        "apt_groups": ["APT33", "Cobalt Strike", "Turla", "FIN7"],
        "cve_examples": [],
        "categories": ["antivirus"],
        "nca_domains": ["2-9"],
        "keywords": "process injection memory antivirus evasion endpoint malware dll injection hollowing APC shellcode reflective loading memory-only",
        "description": "Malware injects code into legitimate Windows processes (svchost, explorer) to hide from AV and operate with elevated privileges.",
        "mitigation": "Deploy behavioral EDR; enable Windows Defender memory protection; use AMSI; monitor for cross-process memory writes."
    },
    {
        "technique_id": "T1036",
        "sub_id": "T1036.005",
        "name": "Masquerading as Legitimate Process",
        "tactic": "Defense Evasion",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.78,
        "apt_groups": ["APT34", "Lazarus", "APT41"],
        "cve_examples": [],
        "categories": ["antivirus", "logging"],
        "nca_domains": ["2-9", "2-18"],
        "keywords": "masquerading legitimate process name rename binary parent process spoof svchost lsass rundll32 fake system process",
        "description": "Malware renames itself or spawns from unexpected parent processes to mimic legitimate Windows system processes.",
        "mitigation": "Deploy process lineage monitoring; alert on svchost/lsass launched from unusual parents; use binary hash validation."
    },
    {
        "technique_id": "T1027",
        "sub_id": None,
        "name": "Obfuscated Files or Information",
        "tactic": "Defense Evasion",
        "severity_score": 7.2,
        "severity_label": "High",
        "prevalence": 0.88,
        "apt_groups": ["APT34", "APT33", "Charming Kitten"],
        "cve_examples": [],
        "categories": ["antivirus"],
        "nca_domains": ["2-9"],
        "keywords": "obfuscation encoding base64 XOR packed binary antivirus bypass detection evasion compressed encrypted payload script",
        "description": "Attackers encode, compress, or encrypt malicious payloads and scripts to evade signature-based detection.",
        "mitigation": "Enable script deobfuscation capabilities in EDR; use behavioral detection; scan compressed archives in email."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # CREDENTIAL ACCESS
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1003",
        "sub_id": "T1003.001",
        "name": "LSASS Memory Dump",
        "tactic": "Credential Access",
        "severity_score": 9.5,
        "severity_label": "Critical",
        "prevalence": 0.92,
        "apt_groups": ["APT33", "APT34", "Lazarus", "FIN7", "CL0P"],
        "cve_examples": [],
        "categories": ["access", "antivirus"],
        "nca_domains": ["2-8", "2-9"],
        "keywords": "mimikatz credential dump LSASS memory password hash NTLM Kerberos golden ticket sekurlsa procdump WDigest cleartext",
        "description": "Attackers dump LSASS process memory using tools like Mimikatz to harvest NTLM hashes and cleartext passwords for lateral movement.",
        "mitigation": "Enable Credential Guard; configure PPL for LSASS; restrict SeDebugPrivilege; detect Mimikatz signatures in EDR."
    },
    {
        "technique_id": "T1110",
        "sub_id": "T1110.003",
        "name": "Password Spraying",
        "tactic": "Credential Access",
        "severity_score": 8.1,
        "severity_label": "High",
        "prevalence": 0.87,
        "apt_groups": ["APT33", "APT29", "Cozy Bear", "Scattered Spider"],
        "cve_examples": [],
        "categories": ["access"],
        "nca_domains": ["2-8"],
        "keywords": "password spray brute force credential attack authentication lockout policy account multiple users single password Azure AD Office 365",
        "description": "Attackers try a single common password against many accounts to avoid lockout thresholds — very effective against cloud identity providers.",
        "mitigation": "Enforce strong password policies; deploy MFA; configure smart lockout in Azure AD; monitor failed auth events."
    },
    {
        "technique_id": "T1110",
        "sub_id": "T1110.004",
        "name": "Credential Stuffing",
        "tactic": "Credential Access",
        "severity_score": 8.0,
        "severity_label": "High",
        "prevalence": 0.83,
        "apt_groups": ["FIN7", "Scattered Spider", "Muddled Libra"],
        "cve_examples": [],
        "categories": ["access"],
        "nca_domains": ["2-8"],
        "keywords": "credential stuffing breach leaked password list automation bot login reuse breached database combo list account takeover",
        "description": "Attackers use breach databases of username/password pairs to test credentials against corporate systems.",
        "mitigation": "Enforce MFA; use HIBP-style breach password detection; deploy bot detection on login endpoints."
    },
    {
        "technique_id": "T1556",
        "sub_id": None,
        "name": "Modify Authentication Process",
        "tactic": "Credential Access / Defense Evasion",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.55,
        "apt_groups": ["APT29", "FIN7", "Muddled Libra"],
        "cve_examples": [],
        "categories": ["access"],
        "nca_domains": ["2-8"],
        "keywords": "authentication bypass MFA modification identity provider credential module SSPI plugin SAML token golden SAML Shibboleth",
        "description": "Adversaries modify authentication mechanisms to bypass MFA or forge authentication tokens (Golden SAML attacks).",
        "mitigation": "Monitor authentication system changes; audit IdP configurations; use certificate-pinned MFA; alert on federation changes."
    },
    {
        "technique_id": "T1552",
        "sub_id": "T1552.001",
        "name": "Credentials in Files",
        "tactic": "Credential Access",
        "severity_score": 8.5,
        "severity_label": "High",
        "prevalence": 0.80,
        "apt_groups": ["APT34", "FIN7", "Lazarus"],
        "cve_examples": [],
        "categories": ["encryption", "access"],
        "nca_domains": ["2-8", "2-13", "2-14"],
        "keywords": "plaintext password unencrypted credential storage config file script web.config bash_profile git repository hardcoded credential",
        "description": "Attackers search for credentials stored in plaintext in configuration files, scripts, and code repositories.",
        "mitigation": "Scan repositories for secrets (git-secrets, TruffleHog); use secrets management; enforce credential encryption."
    },
    {
        "technique_id": "T1539",
        "sub_id": None,
        "name": "Steal Web Session Cookie",
        "tactic": "Credential Access",
        "severity_score": 8.0,
        "severity_label": "High",
        "prevalence": 0.75,
        "apt_groups": ["APT29", "Scattered Spider", "Lapsus$"],
        "cve_examples": [],
        "categories": ["access", "network"],
        "nca_domains": ["2-8", "2-21"],
        "keywords": "session cookie theft MFA bypass token hijack browser cookie steal AiTM adversary-in-the-middle Evilginx phishing token replay",
        "description": "Attackers steal authenticated session cookies via AiTM proxies (Evilginx) to bypass MFA entirely.",
        "mitigation": "Enforce token-binding MFA (FIDO2); use Conditional Access with device compliance; implement CAE."
    },
    {
        "technique_id": "T1558",
        "sub_id": "T1558.003",
        "name": "Kerberoasting",
        "tactic": "Credential Access",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.77,
        "apt_groups": ["APT33", "APT34", "FIN7", "ransomware operators"],
        "cve_examples": [],
        "categories": ["access"],
        "nca_domains": ["2-8"],
        "keywords": "kerberoasting kerberos service ticket TGS request SPN offline crack hash Active Directory domain service account password",
        "description": "Any domain user can request Kerberos service tickets for service accounts; offline cracking recovers passwords for lateral movement.",
        "mitigation": "Use strong passwords (25+) for service accounts; deploy Group Managed Service Accounts (gMSA); monitor anomalous TGS requests."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # DISCOVERY
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1046",
        "sub_id": None,
        "name": "Network Service Discovery",
        "tactic": "Discovery",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.88,
        "apt_groups": ["APT33", "APT34", "Lazarus", "FIN7"],
        "cve_examples": [],
        "categories": ["network", "logging"],
        "nca_domains": ["2-11", "2-18"],
        "keywords": "network scan port discovery service enumeration reconnaissance nmap masscan Shodan service identification asset discovery internal",
        "description": "Attackers map the internal network to identify services, open ports, and pivot targets after initial compromise.",
        "mitigation": "Deploy network IDS/IPS; alert on port scan patterns; use network segmentation; monitor for internal scanning."
    },
    {
        "technique_id": "T1018",
        "sub_id": None,
        "name": "Remote System Discovery",
        "tactic": "Discovery",
        "severity_score": 6.5,
        "severity_label": "Medium",
        "prevalence": 0.85,
        "apt_groups": ["APT33", "APT34", "Lazarus"],
        "cve_examples": [],
        "categories": ["network", "logging"],
        "nca_domains": ["2-11", "2-18"],
        "keywords": "remote system discovery ping sweep ARP DNS zone transfer host enumeration domain controller LDAP query net view",
        "description": "Adversaries enumerate hosts on the network to identify targets for lateral movement.",
        "mitigation": "Monitor for mass ICMP/ARP; restrict DNS zone transfers; log and alert on LDAP enumeration."
    },
    {
        "technique_id": "T1082",
        "sub_id": None,
        "name": "System Information Discovery",
        "tactic": "Discovery",
        "severity_score": 5.5,
        "severity_label": "Medium",
        "prevalence": 0.92,
        "apt_groups": ["APT33", "APT34", "Lazarus", "FIN7"],
        "cve_examples": [],
        "categories": ["logging"],
        "nca_domains": ["2-18"],
        "keywords": "system information OS version hostname environment variable registry query systeminfo ipconfig whoami inventory fingerprint",
        "description": "Malware fingerprints the target system to determine OS, patches, and environment before deploying its payload.",
        "mitigation": "Monitor for bulk systeminfo/ipconfig calls; correlate with anomalous context; use deception (canary data)."
    },
    {
        "technique_id": "T1087",
        "sub_id": "T1087.002",
        "name": "Domain Account Discovery",
        "tactic": "Discovery",
        "severity_score": 6.8,
        "severity_label": "Medium",
        "prevalence": 0.83,
        "apt_groups": ["APT33", "APT34", "APT29"],
        "cve_examples": [],
        "categories": ["logging", "access"],
        "nca_domains": ["2-18", "2-8"],
        "keywords": "account enumeration discovery LDAP AD query net user group admin BloodHound SharpHound domain controller",
        "description": "Attackers enumerate domain accounts, groups, and admin relationships using LDAP queries or BloodHound to plan privilege escalation paths.",
        "mitigation": "Monitor LDAP enumeration; restrict BloodHound-style queries; log domain controller access; use AD tier model."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # LATERAL MOVEMENT
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1210",
        "sub_id": None,
        "name": "Exploitation of Remote Services",
        "tactic": "Lateral Movement",
        "severity_score": 9.0,
        "severity_label": "Critical",
        "prevalence": 0.75,
        "apt_groups": ["APT33", "Lazarus", "NotPetya actors"],
        "cve_examples": ["CVE-2017-0144 (EternalBlue)", "CVE-2020-0796 (SMBGhost)", "CVE-2021-21985 (VMware)"],
        "categories": ["patch", "network"],
        "nca_domains": ["2-11", "2-16"],
        "keywords": "remote exploit service vulnerability unpatched lateral movement SMB RCE EternalBlue WannaCry NotPetya internal network pivot",
        "description": "Attackers exploit unpatched internal network services to move laterally without needing credentials.",
        "mitigation": "Patch internal services urgently; disable SMBv1; segment networks; monitor lateral movement patterns."
    },
    {
        "technique_id": "T1021",
        "sub_id": "T1021.001",
        "name": "Remote Desktop Protocol Lateral Movement",
        "tactic": "Lateral Movement",
        "severity_score": 8.4,
        "severity_label": "High",
        "prevalence": 0.87,
        "apt_groups": ["APT33", "FIN7", "LockBit", "BlackCat"],
        "cve_examples": [],
        "categories": ["network", "access"],
        "nca_domains": ["2-8", "2-11"],
        "keywords": "RDP remote desktop lateral movement stolen credentials pass hash ticket jump workstation server pivot internal",
        "description": "Attackers use stolen credentials to RDP into internal systems and move across the network.",
        "mitigation": "Disable RDP except on bastion hosts; enforce NLA; use PAM; log all RDP sessions."
    },
    {
        "technique_id": "T1021",
        "sub_id": "T1021.002",
        "name": "SMB/Windows Admin Shares",
        "tactic": "Lateral Movement",
        "severity_score": 8.0,
        "severity_label": "High",
        "prevalence": 0.82,
        "apt_groups": ["APT33", "APT34", "Conti", "Ryuk"],
        "cve_examples": [],
        "categories": ["network", "access"],
        "nca_domains": ["2-8", "2-11"],
        "keywords": "SMB admin share C$ ADMIN$ IPC$ lateral movement PsExec wmiexec pass hash NTLM relay credential file transfer",
        "description": "Attackers use Windows admin shares with valid credentials (including Pass-the-Hash) for file transfer and remote execution.",
        "mitigation": "Disable default admin shares where possible; enforce SMB signing; use PAM; segment workstations from servers."
    },
    {
        "technique_id": "T1550",
        "sub_id": "T1550.002",
        "name": "Pass the Hash",
        "tactic": "Lateral Movement / Defense Evasion",
        "severity_score": 8.5,
        "severity_label": "High",
        "prevalence": 0.85,
        "apt_groups": ["APT33", "APT34", "Lazarus", "FIN7"],
        "cve_examples": [],
        "categories": ["access", "network"],
        "nca_domains": ["2-8", "2-11"],
        "keywords": "pass hash PtH NTLM hash lateral movement credential reuse overpass hash LSASS dump authentication bypass",
        "description": "Attackers use harvested NTLM hashes to authenticate to remote systems without knowing the plaintext password.",
        "mitigation": "Enable Protected Users security group; deploy Credential Guard; enforce LAPS for local admin passwords."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # COLLECTION
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1005",
        "sub_id": None,
        "name": "Data from Local System",
        "tactic": "Collection",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.80,
        "apt_groups": ["APT34", "APT33", "Charming Kitten", "FIN7"],
        "cve_examples": [],
        "categories": ["encryption", "logging"],
        "nca_domains": ["2-13", "2-18"],
        "keywords": "data collection local file system sensitive document credential database staged exfiltration search file harvest",
        "description": "Attackers search and collect sensitive files (documents, databases, config files) from compromised systems before exfiltration.",
        "mitigation": "Implement DLP; monitor mass file access events; encrypt sensitive data at rest; use data classification."
    },
    {
        "technique_id": "T1530",
        "sub_id": None,
        "name": "Data from Cloud Storage",
        "tactic": "Collection",
        "severity_score": 8.0,
        "severity_label": "High",
        "prevalence": 0.70,
        "apt_groups": ["APT29", "Scattered Spider", "Lapsus$"],
        "cve_examples": [],
        "categories": ["logging", "encryption"],
        "nca_domains": ["2-13", "2-14", "2-18"],
        "keywords": "cloud storage data exfiltration S3 bucket Azure Blob SharePoint OneDrive unauthorized access audit logging cloud monitoring",
        "description": "Attackers access sensitive data from inadequately monitored or misconfigured cloud storage repositories.",
        "mitigation": "Enable cloud audit logging; enforce access controls; CSPM monitoring; alert on mass data access patterns."
    },
    {
        "technique_id": "T1114",
        "sub_id": "T1114.002",
        "name": "Remote Email Collection",
        "tactic": "Collection",
        "severity_score": 7.8,
        "severity_label": "High",
        "prevalence": 0.72,
        "apt_groups": ["APT34", "APT35", "Charming Kitten", "Phosphorus"],
        "cve_examples": [],
        "categories": ["access", "logging"],
        "nca_domains": ["2-8", "2-10", "2-18"],
        "keywords": "email collection OWA Exchange O365 Graph API mailbox access OAuth application mail forwarding espionage insider",
        "description": "Attackers access and exfiltrate email from Exchange/O365 using compromised credentials or OAuth app permissions.",
        "mitigation": "Monitor OAuth app permissions; audit mailbox delegate access; alert on mass email access; enforce MFA."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # COMMAND AND CONTROL
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1071",
        "sub_id": "T1071.001",
        "name": "Web Protocols C2",
        "tactic": "Command and Control",
        "severity_score": 7.8,
        "severity_label": "High",
        "prevalence": 0.90,
        "apt_groups": ["APT33", "APT34", "Turla", "Cobalt Strike"],
        "cve_examples": [],
        "categories": ["network", "firewall"],
        "nca_domains": ["2-11"],
        "keywords": "C2 command control HTTPS HTTP web traffic beaconing Cobalt Strike Metasploit malware callback encrypted channel tunnel",
        "description": "Malware communicates with C2 servers over standard HTTPS to blend with legitimate web traffic and evade detection.",
        "mitigation": "Deploy SSL/TLS inspection; use DNS filtering; behavioral traffic analysis; block known C2 infrastructure."
    },
    {
        "technique_id": "T1071",
        "sub_id": "T1071.004",
        "name": "DNS C2 / DNS Tunneling",
        "tactic": "Command and Control",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.65,
        "apt_groups": ["APT34", "OilRig", "Turla", "Charming Kitten"],
        "cve_examples": [],
        "categories": ["network", "firewall"],
        "nca_domains": ["2-11"],
        "keywords": "DNS tunnel C2 command control exfiltration covert channel DNS query TXT record dnscat iodine data exfil firewall bypass",
        "description": "Attackers encode data in DNS queries/responses to establish a covert C2 channel that bypasses most firewalls.",
        "mitigation": "Deploy DNS security filtering (Umbrella/Infoblox); monitor DNS query volumes; use RPZ blocklists."
    },
    {
        "technique_id": "T1105",
        "sub_id": None,
        "name": "Ingress Tool Transfer",
        "tactic": "Command and Control",
        "severity_score": 7.8,
        "severity_label": "High",
        "prevalence": 0.85,
        "apt_groups": ["APT33", "APT34", "Lazarus", "FIN7"],
        "cve_examples": [],
        "categories": ["network", "antivirus"],
        "nca_domains": ["2-11", "2-9"],
        "keywords": "tool transfer download additional payload dropper stager certutil bitsadmin curl wget second stage remote file copy",
        "description": "After initial access, attackers download additional tools (stagers, loaders, RATs) to the victim to deploy their full toolkit.",
        "mitigation": "Block outbound file downloads via proxy; whitelist allowed file download sources; monitor certutil/bitsadmin usage."
    },
    {
        "technique_id": "T1571",
        "sub_id": None,
        "name": "Non-Standard Port Communication",
        "tactic": "Command and Control",
        "severity_score": 7.0,
        "severity_label": "High",
        "prevalence": 0.65,
        "apt_groups": ["APT33", "APT34", "Turla"],
        "cve_examples": [],
        "categories": ["network", "firewall"],
        "nca_domains": ["2-11"],
        "keywords": "non-standard port C2 communication tunnel network firewall evasion unusual high port covert channel ICMP",
        "description": "Malware uses unusual or high-numbered ports for C2 communication to evade firewall rules designed for standard ports.",
        "mitigation": "Strict egress filtering whitelist; application-layer firewall inspection; baseline normal port usage per host."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # EXFILTRATION
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1048",
        "sub_id": "T1048.003",
        "name": "Exfiltration over Unencrypted Protocol",
        "tactic": "Exfiltration",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.62,
        "apt_groups": ["APT34", "OilRig", "FIN7"],
        "cve_examples": [],
        "categories": ["encryption", "network"],
        "nca_domains": ["2-13", "2-14", "2-11"],
        "keywords": "data exfiltration FTP HTTP plaintext unencrypted protocol data loss DLP sensitive information transfer bulk upload",
        "description": "Attackers exfiltrate stolen data over unencrypted protocols (FTP, HTTP) that can be detected but are easier to automate.",
        "mitigation": "Block outbound FTP; deploy DLP; enforce HTTPS-only; monitor large outbound data transfers."
    },
    {
        "technique_id": "T1041",
        "sub_id": None,
        "name": "Exfiltration Over C2 Channel",
        "tactic": "Exfiltration",
        "severity_score": 7.8,
        "severity_label": "High",
        "prevalence": 0.78,
        "apt_groups": ["APT33", "APT34", "Lazarus"],
        "cve_examples": [],
        "categories": ["encryption", "network"],
        "nca_domains": ["2-13", "2-11"],
        "keywords": "C2 channel exfiltration data theft encrypted tunnel beacon callback covert channel HTTPS DNS steganography",
        "description": "Stolen data is exfiltrated through the existing encrypted C2 channel, making it hard to distinguish from normal C2 traffic.",
        "mitigation": "Monitor for large outbound payloads in C2 traffic; deploy network behavior analysis (NBA); use UBA."
    },
    {
        "technique_id": "T1020",
        "sub_id": None,
        "name": "Automated Exfiltration",
        "tactic": "Exfiltration",
        "severity_score": 8.1,
        "severity_label": "High",
        "prevalence": 0.70,
        "apt_groups": ["APT34", "Lazarus", "CL0P"],
        "cve_examples": [],
        "categories": ["encryption"],
        "nca_domains": ["2-13"],
        "keywords": "automated exfiltration script scheduled task cron job bulk data transfer archive compress upload automated collection DLP bypass",
        "description": "Attackers deploy scripts or scheduled tasks to continuously collect and exfiltrate sensitive data in bulk.",
        "mitigation": "Implement DLP rules; set data transfer thresholds; monitor for scheduled task creation; use UEBA."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # IMPACT
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1486",
        "sub_id": None,
        "name": "Data Encrypted for Impact (Ransomware)",
        "tactic": "Impact",
        "severity_score": 9.8,
        "severity_label": "Critical",
        "prevalence": 0.95,
        "apt_groups": ["LockBit", "BlackCat/ALPHV", "CL0P", "Royal", "Rhysida", "Black Basta"],
        "cve_examples": ["CVE-2023-34362 (MOVEit)", "CVE-2021-34527 (PrintNightmare)"],
        "categories": ["backup", "encryption"],
        "nca_domains": ["2-15", "2-14", "2-19"],
        "keywords": "ransomware encryption data impact recovery AES RSA lockbit ryuk conti blackcat double extortion backup destruction business disruption",
        "description": "Ransomware encrypts all accessible data and demands payment. Modern variants exfiltrate data before encryption (double extortion).",
        "mitigation": "Maintain offline/immutable backups; test recovery playbooks; deploy ransomware-specific behavioral EDR; segment backups."
    },
    {
        "technique_id": "T1490",
        "sub_id": None,
        "name": "Inhibit System Recovery",
        "tactic": "Impact",
        "severity_score": 9.1,
        "severity_label": "Critical",
        "prevalence": 0.90,
        "apt_groups": ["LockBit", "Conti", "BlackCat", "Ryuk", "Royal"],
        "cve_examples": [],
        "categories": ["backup"],
        "nca_domains": ["2-15"],
        "keywords": "backup deletion shadow copy VSS disable recovery ransomware BCD boot restore wbadmin vssadmin inhibit system recovery",
        "description": "Ransomware deletes all Volume Shadow Copies and backup catalog entries before encrypting to prevent recovery without paying.",
        "mitigation": "Protect VSS with dedicated credentials; use offsite/air-gapped backups; restrict vssadmin/wbadmin to SYSTEM only."
    },
    {
        "technique_id": "T1485",
        "sub_id": None,
        "name": "Data Destruction",
        "tactic": "Impact",
        "severity_score": 9.1,
        "severity_label": "Critical",
        "prevalence": 0.60,
        "apt_groups": ["Sandworm", "APT33 (Shamoon)", "Lazarus (WhisperGate)", "HermeticWiper"],
        "cve_examples": [],
        "categories": ["backup"],
        "nca_domains": ["2-15"],
        "keywords": "data destruction wipe disk Shamoon wiper attack MBR partition overwrite NotPetya WhisperGate destructive cyberattack backup recovery",
        "description": "Nation-state actors deploy destructive wipers (Shamoon, WhisperGate) to permanently destroy data and render systems unusable — common in GCC targeting.",
        "mitigation": "Maintain geographically separate backups; isolate backup networks; implement DR playbooks; monitor for disk write utilities."
    },
    {
        "technique_id": "T1499",
        "sub_id": None,
        "name": "Endpoint Denial of Service",
        "tactic": "Impact",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.68,
        "apt_groups": ["APT33", "Lazarus", "DDoS-as-a-service groups"],
        "cve_examples": [],
        "categories": ["firewall", "network"],
        "nca_domains": ["2-11", "2-19"],
        "keywords": "denial service DDoS flood volumetric amplification application layer HTTP TCP SYN network availability service disruption",
        "description": "Attackers overwhelm network or application resources to deny service to legitimate users.",
        "mitigation": "Deploy DDoS scrubbing services; implement rate limiting; use anycast; configure SYN cookies."
    },
    {
        "technique_id": "T1496",
        "sub_id": None,
        "name": "Resource Hijacking",
        "tactic": "Impact",
        "severity_score": 6.5,
        "severity_label": "Medium",
        "prevalence": 0.60,
        "apt_groups": ["APT41", "TeamTNT", "Rocke"],
        "cve_examples": [],
        "categories": ["network", "antivirus"],
        "nca_domains": ["2-9", "2-11"],
        "keywords": "cryptomining resource hijack coin miner XMRig GPU CPU bandwidth cloud compute abuse cryptojacking",
        "description": "Attackers abuse compromised systems for cryptocurrency mining, degrading performance and increasing infrastructure costs.",
        "mitigation": "Monitor for high CPU/GPU utilization; use endpoint behavioral detection; audit cloud spend anomalies."
    },

    # ══════════════════════════════════════════════════════════════════════════════
    # ADDITIONAL HIGH-VALUE TECHNIQUES
    # ══════════════════════════════════════════════════════════════════════════════
    {
        "technique_id": "T1136",
        "sub_id": "T1136.002",
        "name": "Create Domain Account",
        "tactic": "Persistence",
        "severity_score": 8.5,
        "severity_label": "High",
        "prevalence": 0.65,
        "apt_groups": ["APT29", "Conti", "LockBit operators"],
        "cve_examples": [],
        "categories": ["access"],
        "nca_domains": ["2-8"],
        "keywords": "create domain account backdoor admin account persistence Active Directory domain controller privileged account ghost account",
        "description": "Attackers with domain admin rights create hidden backdoor accounts in Active Directory for long-term persistent access.",
        "mitigation": "Alert on new admin account creation; audit AD for unknown accounts; implement JIT access; use PAM solutions."
    },
    {
        "technique_id": "T1548",
        "sub_id": "T1548.002",
        "name": "UAC Bypass",
        "tactic": "Defense Evasion / Privilege Escalation",
        "severity_score": 7.8,
        "severity_label": "High",
        "prevalence": 0.75,
        "apt_groups": ["APT33", "APT34", "FIN7"],
        "cve_examples": [],
        "categories": ["antivirus", "patch"],
        "nca_domains": ["2-9", "2-16"],
        "keywords": "UAC bypass user account control privilege escalation auto-elevate COM object registry hijack eventvwr fodhelper Windows elevation",
        "description": "Attackers bypass User Account Control to silently elevate privileges without triggering admin prompts.",
        "mitigation": "Set UAC to Always Notify; run as non-admin daily; monitor auto-elevated process events."
    },
    {
        "technique_id": "T1557",
        "sub_id": None,
        "name": "Adversary-in-the-Middle",
        "tactic": "Credential Access / Collection",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.65,
        "apt_groups": ["APT33", "APT34", "Charming Kitten"],
        "cve_examples": [],
        "categories": ["network"],
        "nca_domains": ["2-11", "2-14"],
        "keywords": "man in the middle ARP spoofing LLMNR NBT-NS poisoning NTLM relay Responder network interception credential MiTM SSL strip",
        "description": "Attackers intercept network communications using ARP/LLMNR poisoning to harvest credentials via NTLM relay attacks.",
        "mitigation": "Disable LLMNR/NBT-NS; enforce SMB signing; use encrypted protocols (TLS); deploy 802.1X port authentication."
    },
    {
        "technique_id": "T1040",
        "sub_id": None,
        "name": "Network Sniffing",
        "tactic": "Credential Access / Discovery",
        "severity_score": 7.8,
        "severity_label": "High",
        "prevalence": 0.60,
        "apt_groups": ["APT33", "Turla", "APT34"],
        "cve_examples": [],
        "categories": ["network", "encryption"],
        "nca_domains": ["2-11", "2-14"],
        "keywords": "packet capture sniffing network traffic credentials plaintext Wireshark tcpdump promiscuous mode passive eavesdrop unencrypted",
        "description": "Adversaries capture unencrypted network traffic on compromised hosts or network devices to harvest sensitive data and credentials.",
        "mitigation": "Encrypt all network communications (TLS 1.2+); use mutual TLS; restrict promiscuous mode access."
    },
    {
        "technique_id": "T1053",
        "sub_id": "T1053.005",
        "name": "Scheduled Task Persistence",
        "tactic": "Execution / Persistence / Privilege Escalation",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.80,
        "apt_groups": ["APT33", "FIN7", "Lazarus", "Conti"],
        "cve_examples": [],
        "categories": ["antivirus", "logging"],
        "nca_domains": ["2-9", "2-18"],
        "keywords": "scheduled task schtasks AT command persistence execute autorun task scheduler malware recurring execution stealth cron job",
        "description": "Attackers create Windows scheduled tasks to execute malware at system startup or on a recurring interval.",
        "mitigation": "Monitor scheduled task creation (event 4698); review existing tasks for anomalies; restrict Task Scheduler access."
    },
    {
        "technique_id": "T1219",
        "sub_id": None,
        "name": "Remote Access Software",
        "tactic": "Command and Control",
        "severity_score": 7.8,
        "severity_label": "High",
        "prevalence": 0.78,
        "apt_groups": ["Scattered Spider", "FIN7", "Lapsus$", "BEC groups"],
        "cve_examples": [],
        "categories": ["network", "firewall"],
        "nca_domains": ["2-11", "2-12"],
        "keywords": "remote access tool RAT AnyDesk TeamViewer ScreenConnect Atera RMM dual-use legitimate tool backdoor access",
        "description": "Attackers abuse legitimate remote access tools (AnyDesk, TeamViewer) to establish persistent access while blending with IT activity.",
        "mitigation": "Whitelist approved RMM tools; monitor for unauthorized installations; alert on new remote access software."
    },
    {
        "technique_id": "T1072",
        "sub_id": None,
        "name": "Compromise Software Deployment Tools",
        "tactic": "Execution / Lateral Movement",
        "severity_score": 8.4,
        "severity_label": "High",
        "prevalence": 0.55,
        "apt_groups": ["APT29", "APT41", "Lazarus"],
        "cve_examples": ["CVE-2021-30116 (Kaseya)"],
        "categories": ["patch"],
        "nca_domains": ["2-9", "2-24"],
        "keywords": "software deployment SCCM Intune WSUS patch management tool compromise rogue update distribution server malicious package",
        "description": "Attackers compromise software distribution systems (SCCM, Kaseya) to push malicious payloads to all managed endpoints simultaneously.",
        "mitigation": "Secure patch management infrastructure; validate package signatures; restrict admin access to deployment systems."
    },
    {
        "technique_id": "T1195",
        "sub_id": "T1195.001",
        "name": "Compromise Software Dependencies",
        "tactic": "Initial Access",
        "severity_score": 8.8,
        "severity_label": "High",
        "prevalence": 0.58,
        "apt_groups": ["Lazarus", "APT41"],
        "cve_examples": ["CVE-2021-44228 (Log4Shell npm)", "XZ Utils CVE-2024-3094"],
        "categories": ["patch", "network"],
        "nca_domains": ["2-9", "2-24"],
        "keywords": "dependency supply chain npm pip PyPI typosquatting malicious package open source compromise library injection",
        "description": "Attackers inject malicious code into open-source packages (npm, PyPI) used as dependencies in enterprise software.",
        "mitigation": "Use software composition analysis (SCA); pin dependency versions; scan dependencies for known CVEs (Snyk, Dependabot)."
    },
    {
        "technique_id": "T1578",
        "sub_id": None,
        "name": "Modify Cloud Compute Infrastructure",
        "tactic": "Defense Evasion",
        "severity_score": 7.5,
        "severity_label": "High",
        "prevalence": 0.55,
        "apt_groups": ["APT29", "Scattered Spider"],
        "cve_examples": [],
        "categories": ["logging", "network"],
        "nca_domains": ["2-11", "2-18"],
        "keywords": "cloud compute modify snapshot VM instance firewall security group AWS Azure GCP infrastructure evade detection cloud audit",
        "description": "Attackers modify cloud compute resources, security groups, or snapshot configurations to maintain access and evade detection.",
        "mitigation": "Enable cloud audit logging (CloudTrail/Activity Log); use CSPM; alert on security group modifications."
    },
]
